"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import data from "./sellout-total.json";

const colors = ["#ea580c", "#f97316", "#fb923c", "#fdba74"];
const fmtU = (n: number) => n.toLocaleString("es-MX", { maximumFractionDigits: 0 });
const fmtPvp = (n: number) => `$${n.toLocaleString("es-MX", { maximumFractionDigits: 0 })}`;
const fmtPct = (n: number | null) => n === null ? "—" : `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
function Badge({ value }: { value: number | null }) { const up = value !== null && value >= 0; return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold ${up ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{up ? <ArrowUpRight size={11} /> : <ArrowDownRight size={11} />}{fmtPct(value)}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-xl border border-orange-200 bg-white p-3 shadow-sm ${className}`}>{children}</section>; }
function Header({ title, subtitle }: { title: string; subtitle: string }) { return <header className="mb-3 flex items-center gap-3"><img src="/4buddies-logo.jpeg" alt="4BUDDIES" className="h-10 rounded-lg shadow" /><div><h2 className="text-xl font-black text-orange-950">{title}</h2><p className="text-[11px] font-medium text-orange-700">{subtitle}</p></div></header>; }
function Insight({ children }: { children: React.ReactNode }) { return <div className="mt-3 rounded-lg bg-orange-600 px-4 py-2 text-xs font-semibold text-white">{children}</div>; }
function Table({ children }: { children: React.ReactNode }) { return <table className="w-full text-xs">{children}</table>; }

function Cover() { return <div className="flex h-full flex-col items-center justify-center p-10 text-center"><img src="/4buddies-logo.jpeg" alt="4BUDDIES" className="mb-5 h-24 rounded-2xl shadow-xl" /><p className="mb-2 font-mono text-xs font-bold uppercase tracking-[0.25em] text-orange-600">Resumen ejecutivo · sell-out</p><h1 className="text-4xl font-black tracking-tight text-orange-950">4BUDDIES × Farmacias del Ahorro</h1><p className="mt-2 text-lg text-orange-700">{data.periodo} · corte al 31 de agosto de 2026</p><div className="mt-7 grid grid-cols-4 gap-3 text-left">{[["Venta YTD", `${fmtU(data.kpi.udsYtd26)} uds`, data.kpi.varUds], ["Agosto", `${fmtU(data.kpi.udsAgo26)} uds`, data.kpi.varAgo], ["Mismas tiendas", fmtPct(data.kpi.varMismasTiendas), data.kpi.varMismasTiendas], ["Tiendas activas", String(data.kpi.tiendasActivas), null]].map(([a,b,c]) => <Card key={String(a)} className="w-[170px]"><p className="text-[10px] font-bold uppercase text-orange-600">{a}</p><p className="my-1 text-2xl font-black text-orange-950">{b}</p>{c === null ? <p className="text-[10px] text-slate-500">con venta YTD</p> : <Badge value={Number(c)} />}</Card>)}</div><p className="mt-6 max-w-3xl rounded-lg bg-orange-100 px-4 py-2 text-xs font-semibold text-orange-900">Base: todas las sucursales con sell-out, sin limitar a las 410 tiendas catalogadas. Incluye exclusivamente los 4 SKUs core.</p><p className="mt-3 text-[10px] text-slate-500">Estimado PVP YTD: {fmtPvp(data.kpi.estPvp26)}. Precio de anaquel de referencia; no es facturación real.</p></div>; }

function Monthly() { return <div className="flex h-full flex-col p-6"><Header title="Tendencia mensual" subtitle="Sell-out en unidades · comparación equivalente 2025 vs 2026" /><div className="flex min-h-0 flex-1 gap-3"><Card className="flex-1"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly} margin={{ left: -16 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis dataKey="mes" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="u2025" name="2025" fill="#fdba74" radius={[3,3,0,0]} /><Bar dataKey="u2026" name="2026" fill="#ea580c" radius={[3,3,0,0]} /></BarChart></ResponsiveContainer></Card><Card className="w-[330px]"><Table><thead className="bg-orange-600 text-white"><tr><th className="p-1 text-left">Mes</th><th className="p-1 text-right">2025</th><th className="p-1 text-right">2026</th><th className="p-1 text-right">Var.</th></tr></thead><tbody>{data.monthly.map((m,i) => <tr key={m.mes} className={i%2 ? "bg-orange-50" : ""}><td className="p-1.5 font-semibold">{m.mes}</td><td className="p-1.5 text-right">{fmtU(m.u2025)}</td><td className="p-1.5 text-right font-bold">{fmtU(m.u2026)}</td><td className="p-1.5 text-right"><Badge value={m.var} /></td></tr>)}</tbody></Table></Card></div><Insight>Después de un primer trimestre plano, mayo, julio y agosto aceleran. Agosto cerró {fmtPct(data.kpi.varAgo)} vs agosto de 2025.</Insight></div>; }

function Products() { return <div className="flex h-full flex-col p-6"><Header title="Qué está impulsando la venta" subtitle="Mix YTD de los cuatro SKUs core" /><div className="flex min-h-0 flex-1 gap-4"><Card className="w-[390px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.products} dataKey="uds26" nameKey="corto" cx="50%" cy="46%" outerRadius={115} label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}>{data.products.map((_,i) => <Cell key={i} fill={colors[i]} />)}</Pie><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /></PieChart></ResponsiveContainer></Card><Card className="flex-1"><Table><thead className="bg-orange-600 text-white"><tr><th className="p-2 text-left">Producto</th><th className="p-2 text-right">2025</th><th className="p-2 text-right">2026</th><th className="p-2 text-right">Var.</th><th className="p-2 text-right">Mix</th></tr></thead><tbody>{data.products.map((p,i) => <tr key={p.upc} className={i%2 ? "bg-orange-50" : ""}><td className="p-2 font-bold text-orange-950">{p.corto}</td><td className="p-2 text-right">{fmtU(p.uds25)}</td><td className="p-2 text-right font-bold">{fmtU(p.uds26)}</td><td className="p-2 text-right"><Badge value={p.var} /></td><td className="p-2 text-right">{p.pctTotal}%</td></tr>)}</tbody></Table></Card></div><Insight>Rodajitas lidera el mix ({data.products[0].pctTotal}%), pero cae {fmtPct(data.products[0].var)}: hay que recuperar su rotación sin frenar los tres SKUs que crecen a doble dígito.</Insight></div>; }

function Recent() { const trend = ["Jun", "Jul", "Ago"].map((mes,index) => ({ mes, ...Object.fromEntries(data.products.map(p => [p.corto, p.tend3m[index]])) })); return <div className="flex h-full flex-col p-6"><Header title="Pulso reciente por producto" subtitle="Unidades mensuales · junio a agosto de 2026" /><Card className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{ left: -15, right: 10 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis dataKey="mes" /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{data.products.map((p,i) => <Line key={p.upc} type="monotone" dataKey={p.corto} stroke={colors[i]} strokeWidth={3} dot={{ r: 4 }} />)}</LineChart></ResponsiveContainer></Card><Insight>Rodajitas sigue al alza en agosto; Street Elote desacelera después del pico de julio y merece revisión de exhibición o activación.</Insight></div>; }

function Cedis() { return <div className="flex h-full flex-col p-6"><Header title="Desempeño por CEDIS" subtitle="Comparativo homologable YTD · FDA reclasificó zonas desde abril" /><div className="flex min-h-0 flex-1 gap-3"><Card className="flex-1"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.cedis} layout="vertical" margin={{ left: 15 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis type="number" tick={{ fontSize: 10 }} /><YAxis type="category" dataKey="cedis" tick={{ fontSize: 11 }} width={48} /><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="u2025" name="2025" fill="#fdba74" /><Bar dataKey="u2026" name="2026" fill="#ea580c" /></BarChart></ResponsiveContainer></Card><Card className="w-[320px]"><Table><thead className="bg-orange-600 text-white"><tr><th className="p-1.5 text-left">CEDIS</th><th className="p-1.5 text-right">2026</th><th className="p-1.5 text-right">Var.</th></tr></thead><tbody>{data.cedis.map((x,i) => <tr key={x.cedis} className={i%2 ? "bg-orange-50" : ""}><td className="p-1.5 font-bold">{x.cedis}</td><td className="p-1.5 text-right">{fmtU(x.u2026)}</td><td className="p-1.5 text-right"><Badge value={x.var} /></td></tr>)}</tbody></Table></Card></div><Insight>MRTL (+13.9%), CLCD (+12.1%) y MEAM (+12.4%) son los focos de crecimiento. PEBO cae -7.3% y requiere diagnóstico.</Insight></div>; }

function Zones() { return <div className="flex h-full flex-col p-6"><Header title="Mapa de venta 2026" subtitle="Participación por zona actual · no usar para comparativo YoY" /><div className="flex min-h-0 flex-1 gap-4"><Card className="flex-1"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.zones2026} margin={{ left: -15 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis dataKey="zona" tick={{ fontSize: 10 }} interval={0} angle={-25} textAnchor="end" height={64} /><YAxis tick={{ fontSize: 10 }} /><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /><Bar dataKey="uds" name="YTD 2026" fill="#ea580c" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></Card><Card className="w-[300px]"><p className="mb-3 text-xs font-bold text-orange-950">Lectura operativa</p><ul className="space-y-3 text-xs leading-relaxed text-slate-700"><li><b>Norte</b> es la prioridad con {fmtU(data.zones2026[0].uds)} uds.</li><li><b>Noroeste</b> ya concentra {fmtU(data.zones2026[1].uds)} uds tras la reclasificación.</li><li>Para medir desempeño comparable, usar la lámina de <b>CEDIS</b>.</li></ul></Card></div><Insight>Las zonas muestran la cobertura actual. Para decisiones de tendencia y abasto, el corte por CEDIS es la base correcta.</Insight></div>; }

function Universe() { return <div className="flex h-full flex-col p-6"><Header title="Universo de tiendas: la base completa" subtitle="Este reporte incluye toda sucursal que registró sell-out" /><div className="grid flex-1 grid-cols-3 gap-4"><Card><p className="text-xs font-bold uppercase text-orange-600">Activas YTD</p><p className="mt-4 text-5xl font-black text-orange-950">{fmtU(data.kpi.tiendasActivas)}</p><p className="mt-2 text-sm text-slate-600">sucursales con venta</p></Card><Card><p className="text-xs font-bold uppercase text-orange-600">Catalogadas activas</p><p className="mt-4 text-5xl font-black text-orange-950">{fmtU(data.kpi.catalogadasYtd)}</p><p className="mt-2 text-sm text-slate-600">de las 410 formalmente catalogadas</p></Card><Card><p className="text-xs font-bold uppercase text-orange-600">No catalogadas activas</p><p className="mt-4 text-5xl font-black text-orange-950">{fmtU(data.kpi.noCatalogadasYtd)}</p><p className="mt-2 text-sm text-slate-600">aportan {fmtU(data.kpi.udsNoCatalogadas)} uds YTD</p></Card></div><Insight>El universo no catalogado aporta 11.1% de la venta YTD: es demanda real y una oportunidad de formalización.</Insight></div>; }

function TopStores() { return <div className="flex h-full flex-col p-6"><Header title="Top 20 sucursales" subtitle="Ranking YTD 2026 · universo completo de venta" /><Card className="min-h-0 flex-1"><Table><thead className="bg-orange-600 text-white"><tr><th className="p-1 text-left">#</th><th className="p-1 text-left">Sucursal</th><th className="p-1 text-left">CEDIS</th><th className="p-1 text-left">Zona</th><th className="p-1 text-right">Uds</th><th className="p-1 text-right">Est. PVP*</th></tr></thead><tbody>{data.topStores.map((x,i) => <tr key={x.code} className={i%2 ? "bg-orange-50" : ""}><td className="p-1 text-slate-400">{i+1}</td><td className="p-1 font-bold text-orange-950">{x.tienda}</td><td className="p-1">{x.cedis}</td><td className="p-1">{x.zona}</td><td className="p-1 text-right font-bold">{fmtU(x.uds)}</td><td className="p-1 text-right text-slate-500">{fmtPvp(x.estPvp)}</td></tr>)}</tbody></Table><p className="mt-2 text-[9px] text-slate-500">* Estimado PVP: precio de anaquel de referencia, no facturación real.</p></Card><Insight>Estas tiendas son las primeras candidatas para proteger ejecución, promoción y visibilidad en piso.</Insight></div>; }

function Formats() { return <div className="flex h-full flex-col p-6"><Header title="Formato y oportunidad" subtitle="El crecimiento debe sostenerse donde está el volumen" /><div className="flex flex-1 gap-4"><Card className="flex-1"><Table><thead className="bg-orange-600 text-white"><tr><th className="p-2 text-left">Formato</th><th className="p-2 text-right">2025</th><th className="p-2 text-right">2026</th><th className="p-2 text-right">Var.</th></tr></thead><tbody>{data.formats.map((x,i) => <tr key={x.formato} className={i%2 ? "bg-orange-50" : ""}><td className="p-3 font-bold">{x.formato}</td><td className="p-3 text-right">{fmtU(x.u2025)}</td><td className="p-3 text-right">{fmtU(x.u2026)}</td><td className="p-3 text-right"><Badge value={x.var} /></td></tr>)}</tbody></Table></Card><Card className="w-[380px]"><h3 className="text-lg font-black text-orange-950">Agosto confirmó la recuperación</h3><p className="mt-4 text-5xl font-black text-emerald-700">{fmtPct(data.kpi.varAgo)}</p><p className="mt-2 text-sm text-slate-600">vs agosto de 2025 · {fmtU(data.kpi.udsAgo26)} uds</p><hr className="my-5 border-orange-200" /><p className="text-sm leading-relaxed text-slate-700">PLUS genera más de 98% de las unidades. El plan comercial debe concentrar promoción, visibilidad y seguimiento en ese formato.</p></Card></div><Insight>Prioridad de septiembre: sostener el impulso de agosto en PLUS y recuperar Rodajitas, el SKU más grande del portafolio.</Insight></div>; }

function Actions() { return <div className="flex h-full flex-col p-6"><Header title="Conclusiones y próximos pasos" subtitle="Lectura ejecutiva del sell-out a agosto de 2026" /><div className="grid flex-1 grid-cols-2 gap-4"><Card><p className="font-mono text-xs font-bold uppercase text-red-600">1 · Recuperar</p><h3 className="mt-2 text-lg font-black text-orange-950">Rodajitas</h3><p className="mt-2 text-sm leading-relaxed text-slate-700">32.0% del mix, pero -4.3% YTD. Revisar presencia, exhibición y activación en CEDIS prioritarios.</p></Card><Card><p className="font-mono text-xs font-bold uppercase text-emerald-600">2 · Escalar</p><h3 className="mt-2 text-lg font-black text-orange-950">Los tres SKUs en crecimiento</h3><p className="mt-2 text-sm leading-relaxed text-slate-700">Chicharrón, Classic White y Street Elote crecen a doble dígito. Proteger disponibilidad y repetir los disparadores de julio-agosto.</p></Card><Card><p className="font-mono text-xs font-bold uppercase text-orange-600">3 · Corregir</p><h3 className="mt-2 text-lg font-black text-orange-950">PEBO</h3><p className="mt-2 text-sm leading-relaxed text-slate-700">Único CEDIS con caída YTD (-7.3%). Abrir diagnóstico de tiendas, ejecución y surtido antes del siguiente ciclo.</p></Card><Card><p className="font-mono text-xs font-bold uppercase text-blue-600">4 · Formalizar</p><h3 className="mt-2 text-lg font-black text-orange-950">327 tiendas sin catálogo</h3><p className="mt-2 text-sm leading-relaxed text-slate-700">Ya venden 3,067 uds. Identificar las de mayor rotación y convertir demanda observable en expansión formal.</p></Card></div><Insight>Resultado: +7.5% YTD y +4.5% en mismas tiendas. La venta está creciendo de forma real; el foco es volver sostenible la aceleración reciente.</Insight></div>; }

const slides = [Cover, Monthly, Products, Recent, Cedis, Zones, Universe, TopStores, Formats, Actions];
const titles = ["Portada","Mensual","Productos","Pulso","CEDIS","Zonas","Universo","Top tiendas","Formato","Acciones"];
export default function Page() { const [current, setCurrent] = useState(0); useEffect(() => { const h = (e: KeyboardEvent) => { if (e.key === "ArrowRight" || e.key === " ") setCurrent(c => Math.min(c + 1, 9)); if (e.key === "ArrowLeft") setCurrent(c => Math.max(c - 1, 0)); }; window.addEventListener("keydown", h); return () => window.removeEventListener("keydown", h); }, []); const Slide = slides[current]; return <main className="flex min-h-screen items-center justify-center bg-orange-950 p-4"><div className="relative aspect-video w-[1280px] overflow-hidden rounded-2xl border-2 border-orange-700 bg-gradient-to-br from-orange-50 to-orange-100 shadow-2xl"><Slide /><nav className="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full bg-orange-950/90 px-4 py-1.5 text-white shadow-lg"><button aria-label="Anterior" onClick={() => setCurrent(c => Math.max(c-1,0))} disabled={!current}><ChevronLeft size={16}/></button>{slides.map((_,i) => <button key={i} title={titles[i]} aria-label={titles[i]} onClick={() => setCurrent(i)} className={`h-2 rounded-full transition-all ${i === current ? "w-5 bg-orange-300" : "w-2 bg-orange-700"}`} />)}<button aria-label="Siguiente" onClick={() => setCurrent(c => Math.min(c+1,9))} disabled={current === 9}><ChevronRight size={16}/></button><span className="ml-1 w-28 text-[10px] text-orange-200">{current+1}/10 · {titles[current]}</span></nav></div></main>; }
