"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChevronLeft, ChevronRight, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import data from "./sellout-total.json";

const orange = ["#ea580c", "#f97316", "#fb923c", "#fdba74"];
const fmtU = (n: number) => n.toLocaleString("es-MX", { maximumFractionDigits: 0 });
const fmtPct = (n: number | null) => n === null ? "—" : `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
function Badge({ value }: { value: number | null }) { const up = value !== null && value >= 0; return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-black ${up ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{up ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{fmtPct(value)}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-orange-200 bg-white p-4 shadow-sm ${className}`}>{children}</section>; }
function Header({ title, subtitle }: { title: string; subtitle: string }) { return <header className="mb-4 flex items-center gap-3"><img src="/4buddies-logo.jpeg" alt="4BUDDIES" className="h-11 rounded-xl shadow" /><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-orange-600">Salud del negocio · sell-out</p><h2 className="text-2xl font-black tracking-tight text-orange-950">{title}</h2><p className="text-xs text-orange-700">{subtitle}</p></div></header>; }
function Footer({ children }: { children: React.ReactNode }) { return <div className="mt-4 rounded-xl bg-orange-600 px-4 py-2.5 text-sm font-bold text-white">{children}</div>; }

function Health() { const k = data.kpi; return <div className="flex h-full flex-col p-8"><div className="flex items-start justify-between"><div><p className="font-mono text-xs font-bold uppercase tracking-[0.25em] text-orange-600">4BUDDIES × Farmacias del Ahorro</p><h1 className="mt-2 text-4xl font-black tracking-tight text-orange-950">La salud del negocio es positiva.</h1><p className="mt-2 text-lg text-orange-700">Sell-out ene–ago 2026 · corte al 31 de agosto</p></div><img src="/4buddies-logo.jpeg" alt="4BUDDIES" className="h-20 rounded-2xl shadow-lg" /></div><div className="mt-8 grid flex-1 grid-cols-2 gap-4"><Card className="border-b-4 border-b-emerald-500"><p className="font-mono text-xs font-bold uppercase text-orange-600">Venta YTD</p><p className="mt-2 text-5xl font-black text-orange-950">{fmtU(k.udsYtd26)} <span className="text-2xl">uds</span></p><div className="mt-3"><Badge value={k.varUds} /> <span className="ml-2 text-xs text-slate-500">vs ene–ago 2025</span></div></Card><Card className="border-b-4 border-b-emerald-500"><p className="font-mono text-xs font-bold uppercase text-orange-600">Crecimiento comparable</p><p className="mt-2 text-5xl font-black text-orange-950">{fmtPct(k.varMismasTiendas)}</p><p className="mt-3 text-xs text-slate-600">sobre {fmtU(k.mismasTiendas)} mismas tiendas</p></Card><Card className="border-b-4 border-b-orange-500"><p className="font-mono text-xs font-bold uppercase text-orange-600">Agosto</p><p className="mt-2 text-5xl font-black text-orange-950">{fmtU(k.udsAgo26)} <span className="text-2xl">uds</span></p><div className="mt-3"><Badge value={k.varAgo} /> <span className="ml-2 text-xs text-slate-500">vs agosto 2025</span></div></Card><Card className="border-b-4 border-b-orange-500"><p className="font-mono text-xs font-bold uppercase text-orange-600">Cobertura con venta</p><p className="mt-2 text-5xl font-black text-orange-950">{fmtU(k.tiendasActivas)}</p><p className="mt-3 text-xs text-slate-600">sucursales activas YTD</p></Card></div><Footer>El crecimiento es sano: +7.5% YTD y +4.5% en mismas tiendas. La aceleración de agosto confirma una recuperación real, no solo expansión de cobertura.</Footer><p className="mt-3 text-[10px] text-slate-500">Base: todas las sucursales con sell-out; no limitada a las 410 tiendas catalogadas. Cuatro SKUs core.</p></div>; }

function Trend() { return <div className="flex h-full flex-col p-6"><Header title="La recuperación ganó velocidad" subtitle="Venta mensual en unidades · 2025 vs 2026" /><div className="flex min-h-0 flex-1 gap-4"><Card className="flex-1"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly} margin={{ top: 18, left: -16 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis dataKey="mes" tick={{ fontSize: 12 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /><Legend wrapperStyle={{ fontSize: 12 }} /><Bar dataKey="u2025" name="2025" fill="#fdba74" radius={[4,4,0,0]} label={{ position: "top", formatter: (v: number) => fmtU(v), fill: "#9a3412", fontSize: 10, fontWeight: 700 }} /><Bar dataKey="u2026" name="2026" fill="#ea580c" radius={[4,4,0,0]} label={{ position: "top", formatter: (v: number) => fmtU(v), fill: "#9a3412", fontSize: 10, fontWeight: 700 }} /></BarChart></ResponsiveContainer></Card><Card className="w-[330px]"><p className="font-mono text-xs font-bold uppercase text-orange-600">Lectura del periodo</p><div className="mt-4 space-y-4 text-sm leading-relaxed text-slate-700"><p><b>Primer trimestre:</b> comportamiento estable.</p><p><b>Desde mayo:</b> la venta entra en terreno de crecimiento.</p><p><b>Julio y agosto:</b> consolidan la aceleración, con agosto en <b>{fmtPct(data.kpi.varAgo)}</b> vs 2025.</p></div><div className="mt-6 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Tendencia: positiva y acelerándose.</div></Card></div><Footer>La conversación correcta no es “si el negocio crece”, sino cómo sostener la aceleración de mayo a agosto durante el resto del año.</Footer></div>; }

function Portfolio() { const recent = ["Jun", "Jul", "Ago"].map((mes,index) => ({ mes, ...Object.fromEntries(data.products.map(p => [p.corto, p.tend3m[index]])) })); return <div className="flex h-full flex-col p-6"><Header title="Portafolio sano, con una alerta puntual" subtitle="Mix y desempeño YTD de los cuatro SKUs core" /><div className="flex min-h-0 flex-1 gap-4"><Card className="w-[330px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.products} dataKey="uds26" nameKey="corto" cx="50%" cy="46%" outerRadius={105} label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}>{data.products.map((_,i) => <Cell key={i} fill={orange[i]} />)}</Pie><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /></PieChart></ResponsiveContainer></Card><Card className="flex-1"><table className="w-full text-sm"><thead className="bg-orange-600 text-white"><tr><th className="p-2 text-left">SKU</th><th className="p-2 text-right">YTD 2026</th><th className="p-2 text-right">Var.</th><th className="p-2 text-right">Mix</th></tr></thead><tbody>{data.products.map((p,i) => <tr key={p.upc} className={i%2 ? "bg-orange-50" : ""}><td className="p-2 font-bold text-orange-950">{p.corto}</td><td className="p-2 text-right font-bold">{fmtU(p.uds26)}</td><td className="p-2 text-right"><Badge value={p.var} /></td><td className="p-2 text-right">{p.pctTotal}%</td></tr>)}</tbody></table><div className="mt-4 h-[120px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={recent}><XAxis dataKey="mes" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip />{data.products.map((p,i) => <Line key={p.upc} type="monotone" dataKey={p.corto} stroke={orange[i]} strokeWidth={2.5} dot={{ r: 3 }} />)}</LineChart></ResponsiveContainer></div></Card></div><Footer>Rodajitas es 32% del negocio, pero cae -4.3% YTD: es el único foco de salud del portafolio. Los otros tres SKUs compensan con crecimiento a doble dígito.</Footer></div>; }

function Geography() { return <div className="flex h-full flex-col p-6"><Header title="Geografía: seis CEDIS sanos; PEBO requiere atención" subtitle="Comparativo YTD por CEDIS · base comparable ante la reclasificación de zonas FDA" /><div className="flex min-h-0 flex-1 gap-4"><Card className="flex-1"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.cedis} layout="vertical" margin={{ left: 15 }}><CartesianGrid strokeDasharray="3 3" stroke="#fed7aa" /><XAxis type="number" tick={{ fontSize: 10 }} /><YAxis type="category" dataKey="cedis" tick={{ fontSize: 12 }} width={50} /><Tooltip formatter={(v: number) => `${fmtU(v)} uds`} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="u2025" name="2025" fill="#fdba74" /><Bar dataKey="u2026" name="2026" fill="#ea580c" /></BarChart></ResponsiveContainer></Card><Card className="w-[330px]"><p className="font-mono text-xs font-bold uppercase text-orange-600">Lectura ejecutiva</p><div className="mt-4 space-y-4 text-sm text-slate-700"><p><b className="text-emerald-700">Crecimiento:</b> MRTL (+13.9%), MEAM (+12.4%) y CLCD (+12.1%).</p><p><b className="text-orange-800">Estable:</b> MTNA (+0.9%), el CEDIS de mayor volumen.</p><p><b className="text-red-700">Foco:</b> PEBO (-7.3%), único CEDIS con caída YTD.</p></div><div className="mt-6 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">Prioridad: entender el origen de PEBO antes de que afecte la tendencia total.</div></Card></div><Footer>Conclusión: la salud geográfica es positiva y diversificada. La única excepción es PEBO; el siguiente paso es aislar si el freno está en rotación, cobertura o ejecución.</Footer></div>; }

const slides = [Health, Trend, Portfolio, Geography];
const titles = ["Salud", "Tendencia", "Portafolio", "CEDIS"];
export default function Page() { const [current, setCurrent] = useState(0); useEffect(() => { const h = (e: KeyboardEvent) => { if (e.key === "ArrowRight" || e.key === " ") setCurrent(c => Math.min(c + 1, slides.length - 1)); if (e.key === "ArrowLeft") setCurrent(c => Math.max(c - 1, 0)); }; window.addEventListener("keydown", h); return () => window.removeEventListener("keydown", h); }, []); const Slide = slides[current]; return <main className="flex min-h-screen items-center justify-center bg-orange-950 p-4"><div className="relative aspect-video w-[1280px] overflow-hidden rounded-2xl border-2 border-orange-700 bg-gradient-to-br from-orange-50 to-orange-100 shadow-2xl"><Slide /><nav className="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full bg-orange-950/90 px-4 py-1.5 text-white shadow-lg"><button onClick={() => setCurrent(c => Math.max(c - 1, 0))} disabled={!current} aria-label="Anterior" className="disabled:opacity-30"><ChevronLeft size={17} /></button>{slides.map((_,i) => <button key={i} onClick={() => setCurrent(i)} title={titles[i]} aria-label={titles[i]} className={`h-2 rounded-full transition-all ${i === current ? "w-6 bg-orange-300" : "w-2 bg-orange-700 hover:bg-orange-400"}`} />)}<button onClick={() => setCurrent(c => Math.min(c + 1, slides.length - 1))} disabled={current === slides.length - 1} aria-label="Siguiente" className="disabled:opacity-30"><ChevronRight size={17} /></button><span className="ml-1 w-24 text-[10px] text-orange-200">{current+1}/4 · {titles[current]}</span></nav></div></main>; }
